Repository mesh-adaptation/UM2N, pull requests merged in 2024-12, with the labels that each got.

#63 Fix path to docs repo
  .github/workflows/test_suite.yml
Labels: bug, PRIORITY, testing

#64 Simplify test workflow file
  .github/workflows/test_suite.yml
Labels: clarity, testing

#65 Make dev dependencies optional
  Makefile
  pyproject.toml
Labels: install
